name: aspects-poc-reporting
base: core22
version: "0.2"
license: GPL-2.0-only
summary: Snap that consumes confdb config.
description: |
  This snap collects metrics from the device and reports them
  on a cadence.

grade: devel
confinement: devmode

environment:
  ACCOUNT_ID: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN

apps:
  daemon:
    command: bin/reporter-cli
    daemon: simple

parts:
  reporter:
    plugin: python
    source: .
    parse-info:
      - setup.py
    python-packages:
      - snap-http==1.4.0
